from pyfiglet import figlet_format
from termcolor import colored
from faker import Faker
art = figlet_format('HOAXES-D',font='banner3')
art1 = colored(art,'red')
ver = colored("Version 1.0.0",'magenta')
print('\n'+art1+"\t"+ver)
tag = colored("This tool is for educational purposes only",'blue',attrs=['bold'])
author = colored("@author->ishanjogalekar",'green')
print("\n"+tag+"\t"+author)
fake = Faker()
print("\nName: ", fake.name())
print("Email: ", fake.email())
print("Country: ", fake.country())
print("Website URL: ", fake.url())
print("IPv4: ", fake.ipv4())
print("Address: ", fake.address())
print("Job: "+fake.job())
print("Location: ")
print(fake.location_on_land())
print("Company: ",fake.bs())
print("\nRandom Text: ", fake.text())
print("\nCredit card details-> "+"\nCredit card no:"+fake.credit_card_number()+"\nProvider:"+fake.credit_card_provider()+"\nExp.Date:"+fake.credit_card_expire()+"\nCVV:"+fake.credit_card_security_code())
print("\n")
